[package]
name = "doge-bridge-block-state"
version = "0.1.0"
edition = "2021"

[features]
default = ["serialize_borsh", "sha2", "serialize_bytemuck", "serialize_speedy"]
serialize_borsh = ["dep:borsh", "doge-light-client/serialize_borsh"]
serialize_serde = ["dep:serde", "dep:serde_with", "doge-light-client/serialize_serde"]
bitcoin = ["dep:bitcoin", "serialize_serde", "doge-light-client/serialize_serde"]
solprogram = ["dep:solana-program", "doge-light-client/solprogram"]
sha2 = ["dep:sha2", "doge-light-client/sha2"]
std = ["doge-light-client/std"]

serialize_speedy = ["dep:speedy", "doge-light-client/serialize_speedy"]
serialize_bytemuck = ["dep:bytemuck", "doge-light-client/serialize_bytemuck"]

[dependencies]
serde = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true }
bs58 = { workspace = true }
ripemd = { workspace = true }
scrypt = { workspace = true }
borsh = { workspace = true, optional = true }
thiserror = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }

bytemuck = { workspace = true, optional = true }
speedy = { workspace = true, optional = true }
bitcoin = { workspace = true, optional = true }
anyhow = { workspace = true }

solana-program = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
doge-light-client = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
hex-literal = { workspace = true }
bitcoin = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
